---
name: MooseX-Storage-File_or_DB
version: 0.1
author:
  - 'Andy Brown <setitesuk@gmail.com>'
abstract: module to add functions which will store out to a database as well as a file which contains a JSON string
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 1.02
  Config::IniFiles: 2.38
  DBI: 1.51
  English: 1.01
  Moose: 0
  MooseX::InsideOut: 0
  MooseX::Storage: 0
  Readonly: 1.03
  strict: 0
  warnings: 0
build_requires:
  Test::Distribution: 0
  Test::Exception: 0
  Test::More: 0.8
  Test::Perl::Critic: 0
generated_by: Module::Build version 0.32
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
